### ISSUE TITLE
Missing Tiller v2.10.0 ?

### ISSUE THREAD

**Issue by nlamirault** [jessestuart/tiller-multiarch#3]
There is a new version of Helm [v2.10.0](https://github.com/helm/helm/releases/tag/v2.10.0) and the Docker image is of Tiller exist [v2.10.0](https://console.cloud.google.com/gcr/images/kubernetes-helm/GLOBAL/tiller@sha256:2a3dd484ecfcf9343994e0f6c2af0a6faf1af7f7e499905793643f91e90edcb3/details?tab=info)

Do you plan to build this image ?

**Comment by vielmetti** [comment]
I dont' see a 2.10.0 in the repo at https://hub.docker.com/r/jessestuart/tiller/tags/ but there is a even more new 2.12.0 out there as of 6 hours ago.

**Comment by ryanhartje** [comment]
I think this can be closed now:
https://hub.docker.com/r/jessestuart/tiller/tags

What do you think @nlamirault ?

**Comment by nlamirault** [comment]
Great
